### ISSUE TITLE
No sound from iSight camera

### ISSUE THREAD

**Issue by mediter** [brutella/hkcam#13]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brutella** [comment]
Audio support is currently not implemented because audio is problematic on the RPi.
Audio support on a Mac should be possible, but I haven't looked into it yet.

**Comment by deviantintegral** [comment]
What sort of problems does audio have? Is it specific to hkcam for any audio source or just iSights?

I'm looking at using hkcam as an indoor camera solution where audio would be pretty valuable.

**Comment by brutella** [comment]
As stated above, audio support is not implemented because audio on the Raspberry Pi is an easy thing to do.
Since this project is mainly focused on the Raspberry Pi, I haven't focused on the audio part yet.

There is no technical reason why this shouldn't work – I just didn't have time to take a look at it.

**Comment by brutella** [comment]
There are currently no plans to support audio in hkcam. It's just too fiddly on Linux.
