### ISSUE TITLE
Clone /dev/video0 to a second virtual device and keep this loopback open

### ISSUE THREAD

**Issue by Kienz** [brutella/hkcam#65]
Is it possible to clone the video vom /dev/video0 to another virtual device (eg. /dev/video2) and keep this loopback open?
I want to use hkcam and zbarimg (to scan qrcodes) on the same Raspberry Pi.

**Comment by brutella** [comment]
Since version [0.1.0](https://github.com/brutella/hkcam/releases/tag/v0.1.0), the video from `/dev/video0` is copied to `/dev/video99`. The loopback is started and stopped automatically once if someone is requesting the video.

If you want, you could start the loopback manually (outside of `hkcam`) and set the `loopback_filename` to an empty string and the `input_filename` to your loopback file when running `hkcam`.
